/**
 * ipf_render.spec.ts — render the reduced-IPF RGB map the two ways SpyDE can,
 * and screenshot them to compare against the matplotlib reference
 * (tests/fixtures/ipf_ref.png):
 *
 *   ipf_direct.png  — anyplotlib ax.imshow(rgb)                (embedded RGB)
 *   ipf_live.png    — anyplotlib imshow(scalar) + a live set_data(rgb) push
 *                     (exactly what the SpyDE IPF window does today)
 *
 * Assets are generated by tests/fixtures/gen_ipf.py. Loaded in a plain chromium
 * page (the figure HTML is self-contained bar a shared-ESM temp file).
 */
import { test, expect, _electron as electron, ElectronApplication, Page } from '@playwright/test'
import { join } from 'path'
import { readFileSync, existsSync } from 'fs'
import { execSync } from 'child_process'

const FIX = join(__dirname, 'fixtures')
const OUT = join(__dirname, '..')
const REPO = join(__dirname, '..', '..')

let app: ElectronApplication
let page: Page

test.beforeAll(async () => {
  // Regenerate the IPF fixtures fresh — the figure HTML imports a per-session
  // temp ESM, so a stale committed fixture would point at a missing file.
  execSync('uv run electron/tests/fixtures/gen_ipf.py', { cwd: REPO, stdio: 'ignore' })
  if (!existsSync(join(FIX, 'ipf_live_scalar.html'))) throw new Error('gen_ipf.py did not produce fixtures')

  app = await electron.launch({
    args: [join(__dirname, '..', 'out', 'main', 'index.js')],
    env: { ...process.env, SPYDE_NO_DASK: '1' },
  })
  page = await app.firstWindow()
  await page.waitForLoadState('domcontentloaded')
})
test.afterAll(async () => { await app?.close() })

async function brightestPixel(page: import('@playwright/test').Page) {
  // Read the figure canvas pixels → {r,g,b max} so we can assert it's not grey.
  return page.evaluate(() => {
    const cs = Array.from(document.querySelectorAll('canvas')) as HTMLCanvasElement[]
    let best = { colorful: 0, max: 0 }
    for (const c of cs) {
      const ctx = c.getContext('2d'); if (!ctx || !c.width) continue
      const { data } = ctx.getImageData(0, 0, c.width, c.height)
      for (let i = 0; i < data.length; i += 4) {
        const r = data[i], g = data[i + 1], b = data[i + 2]
        const mx = Math.max(r, g, b), mn = Math.min(r, g, b)
        best.colorful = Math.max(best.colorful, mx - mn)   // 0 ⇒ pure grey
        best.max = Math.max(best.max, mx)
      }
    }
    return best
  })
}

test('IPF RGB renders in colour (direct + live set_data paths)', async () => {
  // 1) Direct imshow(rgb)
  await page.goto('file://' + join(FIX, 'ipf_direct.html'))
  await page.waitForTimeout(1400)
  await page.screenshot({ path: join(OUT, 'ipf_direct.png') })
  const direct = await brightestPixel(page)

  // 2) Live path: scalar figure + the captured set_data(rgb) state push.
  await page.goto('file://' + join(FIX, 'ipf_live_scalar.html'))
  await page.waitForTimeout(900)
  const updates = JSON.parse(readFileSync(join(FIX, 'ipf_live_updates.json'), 'utf8'))
  await page.evaluate((ups) => {
    for (const u of ups) window.postMessage({ type: 'awi_state', key: u.key, value: u.value }, '*')
  }, updates)
  await page.waitForTimeout(1400)
  await page.screenshot({ path: join(OUT, 'ipf_live.png') })
  const live = await brightestPixel(page)

  console.log('IPF direct pixels:', JSON.stringify(direct))
  console.log('IPF live   pixels:', JSON.stringify(live))
  // A correct IPF is strongly chromatic (red/green/blue) — grey would mean the
  // RGB was wrongly run through a colormap.
  expect(direct.colorful).toBeGreaterThan(60)
  expect(live.colorful).toBeGreaterThan(60)
})
