/**
 * ipf_refine_render.spec.ts — the OM refine IPF correlation-heatmap panel
 * (real Silver library) renders as a coloured triangle with outline + labels +
 * best-match marker + mask circle. Fixture generated by gen_ipf_refine.py.
 */
import { test, expect, _electron as electron, ElectronApplication, Page } from '@playwright/test'
import { join } from 'path'
import { execSync } from 'child_process'
import { existsSync } from 'fs'

const FIX = join(__dirname, 'fixtures')
const OUT = join(__dirname, '..')
const REPO = join(__dirname, '..', '..')

let app: ElectronApplication
let page: Page

test.beforeAll(async () => {
  execSync('uv run electron/tests/fixtures/gen_ipf_refine.py', { cwd: REPO, stdio: 'ignore' })
  if (!existsSync(join(FIX, 'ipf_refine.html'))) throw new Error('gen_ipf_refine.py produced no fixture')
  app = await electron.launch({
    args: [join(__dirname, '..', 'out', 'main', 'index.js')],
    env: { ...process.env, SPYDE_NO_DASK: '1' },
  })
  page = await app.firstWindow()
  await page.waitForLoadState('domcontentloaded')
})
test.afterAll(async () => { await app?.close() })

test('refine IPF heatmap panel renders in colour', async () => {
  await page.goto('file://' + join(FIX, 'ipf_refine.html'))
  await page.waitForTimeout(1600)
  await page.screenshot({ path: join(OUT, 'ipf_refine.png') })

  const stats = await page.evaluate(() => {
    const cs = Array.from(document.querySelectorAll('canvas')) as HTMLCanvasElement[]
    let colorful = 0
    for (const c of cs) {
      const ctx = c.getContext('2d'); if (!ctx || !c.width) continue
      const { data } = ctx.getImageData(0, 0, c.width, c.height)
      for (let i = 0; i < data.length; i += 4) {
        const mx = Math.max(data[i], data[i + 1], data[i + 2])
        const mn = Math.min(data[i], data[i + 1], data[i + 2])
        colorful = Math.max(colorful, mx - mn)
      }
    }
    return { colorful }
  })
  console.log('refine heatmap pixels:', JSON.stringify(stats))
  expect(stats.colorful).toBeGreaterThan(60)   // a real (chromatic) heatmap
})
