/**
 * talk_present.spec.ts — open the committed SpyDE overview deck in the REAL app
 * and screenshot EVERY slide in Present mode.
 *
 * The deck (`doc/presentations/spyde-overview.spyde-report`) is built by
 * `doc/presentations/build_spyde_overview.py`. It carries only markdown / image /
 * split cells — no live figure bindings — so it opens standalone with no data
 * loaded and needs no Dask.
 *
 * This is the verification the presentation is judged by: every shot in
 * `talk_present_shots/` gets looked at. Text that overflows its slide, an empty
 * figure box, or a blank slide is a FAILURE even when the selectors pass.
 *
 * Run:
 *   npx playwright test tests/talk_present.spec.ts --project=electron \
 *     --reporter=line --retries=0
 */
import { test, expect } from '@playwright/test'
import { join } from 'path'
import { mkdirSync } from 'fs'
const { launchApp, backendAction, backendErrorLines } = require('./_harness.cjs')

const SHOTS = join(__dirname, '..', 'talk_present_shots')
const DECK = join(__dirname, '..', '..', 'doc', 'presentations',
                  'spyde-overview.spyde-report')
/**
 * The slide count is DISCOVERED, not hard-coded.
 *
 * This deck is a live document: it is generated by build_spyde_overview.py, but
 * it is also opened and edited in the app — that is the whole point of shipping
 * a talk as a SpyDE file rather than a PDF. A constant here made the spec assert
 * against whichever version happened to be on disk, and it failed with a
 * different number every run while someone was editing it. What this spec is
 * actually for is "the committed deck presents cleanly", which is true of any
 * slide count.
 */
async function settledSlideCount(page: any): Promise<number> {
  let last = -1, stable = 0
  for (let i = 0; i < 60 && stable < 3; i++) {
    const n = await page.getByTestId(/^report-slide-\d+$/).count()
    stable = n === last ? stable + 1 : 0
    last = n
    await page.waitForTimeout(400)
  }
  return last
}

let ctx: Awaited<ReturnType<typeof launchApp>>

test.describe.configure({ mode: 'serial' })
test.setTimeout(300_000)

test.beforeAll(async () => {
  mkdirSync(SHOTS, { recursive: true })
  ctx = await launchApp({ env: { SPYDE_LOG_LEVEL: 'WARNING' } })
  await ctx.page.waitForTimeout(1500)
})

test.afterAll(async () => {
  try { ctx?.assertNoJsErrors() } finally { await ctx?.app?.close() }
})

test('the committed deck opens and presents cleanly', async () => {
  const { page } = ctx

  // Open the report sidebar, then load the committed deck through the SAME
  // backend handler the sidebar's Open button calls.
  await page.getByTestId('toggle-report').click()
  await expect(page.getByTestId('report-sidebar')).toBeVisible()
  await backendAction(page, 'report_open', { path: DECK })

  // The sidebar mirrors report_state: wait for the deck's slides to arrive and
  // SETTLE, then take that as the count to page through.
  const N_SLIDES = await settledSlideCount(page)
  expect(N_SLIDES, 'report_open produced no slides').toBeGreaterThan(1)
  await page.waitForTimeout(1200)
  await page.screenshot({ path: join(SHOTS, '00-sidebar.png') })

  // Enter Present mode.
  await page.getByTestId('report-present').click()
  const stage = page.locator('[data-testid="present-slide"][data-active="1"]')
  await expect(stage).toBeVisible({ timeout: 30_000 })
  await page.waitForTimeout(1500)

  // The deck carries its own theme. Asserted RELATIVELY — the deck's painted
  // background must equal the theme variable it publishes — rather than against
  // a hard-coded hex: the failure worth catching is a theme that round-trips
  // through the front matter perfectly and then loses to a hard-coded stylesheet
  // rule, and that is true whatever colours the author picked.
  const deck = page.getByTestId('present-mode')
  const themed = await deck.evaluate((el) => {
    const cs = getComputedStyle(el)
    const hex = (h: string) => {
      const m = h.trim().replace('#', '')
      if (m.length !== 6) return h.trim()
      return `rgb(${parseInt(m.slice(0, 2), 16)}, ${parseInt(m.slice(2, 4), 16)}, ` +
             `${parseInt(m.slice(4, 6), 16)})`
    }
    return { bg: cs.backgroundColor,
             bgVar: hex(cs.getPropertyValue('--spyde-deck-bg')),
             textVar: hex(cs.getPropertyValue('--spyde-deck-text')),
             accent: cs.getPropertyValue('--spyde-deck-accent').trim() }
  })
  expect(themed.bg, 'the deck is not painted with its own theme background')
    .toBe(themed.bgVar)
  expect(themed.accent, 'the deck publishes no accent').not.toBe('')

  // Present mode keeps EVERY slide mounted, so a bare locator matches them all —
  // scope to the active stage. A title card carries its own attribution, so the
  // footer belongs on every OTHER slide; the count is derived rather than fixed.
  await expect(stage.getByTestId('present-footer'),
               'the title slide must not carry the footer bar').toHaveCount(0)
  const titleCards = await page.locator(
    '[data-testid="present-slide"][data-kind="title"]').count()
  await expect(page.getByTestId('present-footer'),
               'footer count != non-title slides')
    .toHaveCount(N_SLIDES - titleCards)

  // Page through EVERY slide, screenshotting each. Assert the active slide
  // actually carries rendered text (a blank stage is the failure mode that
  // selectors alone miss), and that nothing overflows the viewport.
  for (let i = 1; i <= N_SLIDES; i++) {
    await page.waitForTimeout(650)                 // let the slide settle/paint
    const n = String(i).padStart(2, '0')
    await page.screenshot({ path: join(SHOTS, `${n}-slide.png`) })

    const text = ((await stage.innerText()) || '').trim()
    expect(text.length, `slide ${i} rendered no text`).toBeGreaterThan(10)

    // The first CONTENT slide: the footer bar, its embedded logo, and the themed
    // heading colour. Checked once rather than per slide — the same component
    // draws the footer every time.
    if (i === 2 && (await stage.getAttribute('data-kind')) === 'content') {
      await expect(stage.getByTestId('present-footer')).toBeVisible()
      await expect(stage.getByTestId('present-footer-logo')).toBeVisible()
      await expect(stage.getByTestId('present-footer-text')).not.toBeEmpty()
      // The base .present-md sheet hard-codes a heading colour that beats the
      // inherited one; this is the assertion that catches a themed deck whose
      // headings stay stock lavender. Compared against the deck's OWN text
      // variable so it holds for any palette the author chose.
      const h2 = stage.locator('h2').first()
      if (await h2.count()) {
        expect(await h2.evaluate((el) => getComputedStyle(el).color),
               'slide headings ignore the deck theme').toBe(themed.textVar)
      }
    }

    // Overflow guard: the slide's content must fit its own scroll box.
    const overflow = await stage.evaluate((el: HTMLElement) => ({
      v: el.scrollHeight - el.clientHeight,
      h: el.scrollWidth - el.clientWidth,
    }))
    expect(overflow.h, `slide ${i} overflows HORIZONTALLY`).toBeLessThanOrEqual(2)
    if (overflow.v > 2) console.log(`  ! slide ${i} overflows vertically by ${overflow.v}px`)

    if (i < N_SLIDES) await page.keyboard.press('ArrowRight')
  }

  // The presenter view (S) — speaker notes must be visible to the presenter.
  await page.keyboard.press('Home')
  await page.waitForTimeout(500)
  await page.keyboard.press('s')
  await page.waitForTimeout(1200)
  await page.screenshot({ path: join(SHOTS, '22-presenter-view.png') })

  // ESC exits.
  await page.keyboard.press('s')
  await page.waitForTimeout(300)
  await page.keyboard.press('Escape')
  await expect(stage).toBeHidden({ timeout: 15_000 })

  const errs = backendErrorLines(ctx.backend)
  expect(errs, `backend errors:\n${errs.join('\n')}`).toEqual([])
})
