/**
 * visual.spec.ts — VISUAL self-checks: the canvas must actually render data.
 *
 * These read the real anyplotlib <canvas> pixels inside the figure iframe and
 * assert the image is NOT black — catching the class of bug ("image is still
 * black") that message-level tests miss. Fixtures are real anyplotlib HTML
 * generated by tests/fixtures/gen_fixtures.py.
 *
 * Self-contained (Node 23 + Playwright 1.61 break on cross-file .ts imports).
 */
import { test, expect, _electron as electron, ElectronApplication, Page, Frame } from '@playwright/test'
import { join } from 'path'
import { readFileSync } from 'fs'

let app: ElectronApplication
let page: Page

const FIXTURES = join(__dirname, 'fixtures')
const brightHtml = readFileSync(join(FIXTURES, 'real_bright.html'), 'utf8')
const placeholderHtml = readFileSync(join(FIXTURES, 'black_placeholder.html'), 'utf8')
const replayState = JSON.parse(readFileSync(join(FIXTURES, 'replay_state.json'), 'utf8'))

test.beforeAll(async () => {
  app = await electron.launch({
    args: [join(__dirname, '..', 'out', 'main', 'index.js')],
    env: { ...process.env, SPYDE_NO_DASK: '1' },
  })
  page = await app.firstWindow()
  await page.waitForLoadState('domcontentloaded')
})
test.afterAll(async () => { await app?.close() })

test.beforeEach(async () => {
  await page.reload()
  await page.waitForSelector('[data-testid="mdi-area"]')
})

async function inject(msg: Record<string, unknown>) {
  await page.evaluate((m) => { (window as any)._spyde_test_inject?.(m) }, msg)
}

// Find the figure iframe's Frame and read the brightest canvas pixel. Polls
// until max exceeds `want` (the real data has rendered) — not merely until
// non-zero, because the placeholder/partial paint can have small values on a
// cold start (which made the replay test flaky). Times out generously (~12s)
// to absorb the first-figure V8 compile of the shared bundle.
async function canvasStats(want = 0): Promise<{ min: number; max: number }> {
  let frame: Frame | undefined
  for (let i = 0; i < 50 && !frame; i++) {
    frame = page.frames().find(f => f !== page.mainFrame())
    if (!frame) await page.waitForTimeout(100)
  }
  if (!frame) throw new Error('figure iframe not found')

  let best = { min: 0, max: 0 }
  for (let i = 0; i < 80; i++) {
    const stats = await frame.evaluate(() => {
      const canvases = Array.from(document.querySelectorAll('canvas')) as HTMLCanvasElement[]
      let min = 255, max = 0
      for (const c of canvases) {
        const ctx = c.getContext('2d')
        if (!ctx) continue
        const { data } = ctx.getImageData(0, 0, c.width, c.height)
        for (let k = 0; k < data.length; k += 4) {
          for (let ch = 0; ch < 3; ch++) {
            const v = data[k + ch]
            if (v < min) min = v
            if (v > max) max = v
          }
        }
      }
      return { min, max }
    })
    if (stats) best = stats
    if (best.max > want) return best
    await page.waitForTimeout(150)
  }
  return best
}

test('a figure with real data renders a NON-BLACK canvas', async () => {
  await inject({
    type: 'figure', window_id: 0, fig_id: 'bright',
    html: brightHtml, title: 'Bright', is_navigator: false,
  })
  const { max } = await canvasStats(40)
  // A viridis gradient must produce bright pixels — black image would be max≈0.
  expect(max).toBeGreaterThan(40)
})

test('figures render in dark mode', async () => {
  await inject({
    type: 'figure', window_id: 0, fig_id: 'bright',
    html: brightHtml, title: 'Bright', is_navigator: false,
  })
  let frame: Frame | undefined
  for (let i = 0; i < 50 && !frame; i++) {
    frame = page.frames().find(f => f !== page.mainFrame())
    if (!frame) await page.waitForTimeout(100)
  }
  // The figure page has a dark background, which is what anyplotlib's _isDarkBg
  // detects to choose the dark theme.
  const bg = await frame!.evaluate(
    () => getComputedStyle(document.body).backgroundColor,
  )
  const m = bg.match(/rgba?\((\d+),\s*(\d+),\s*(\d+)/)
  expect(m, `body bg not parseable: ${bg}`).toBeTruthy()
  const lum = 0.299 * +m![1] + 0.587 * +m![2] + 0.114 * +m![3]
  expect(lum).toBeLessThan(128) // dark
})

test('a state_update repaints a black placeholder with real data', async () => {
  await inject({
    type: 'figure', window_id: 1, fig_id: 'replay',
    html: placeholderHtml, title: 'Replay', is_navigator: false,
  })
  // Placeholder is zeros → black.
  // Now push the real-data panel state (as Python would after creating the fig).
  for (const s of replayState.states) {
    await inject({ type: 'state_update', fig_id: 'replay', key: s.key, value: s.value })
  }
  const { max } = await canvasStats(40)
  expect(max).toBeGreaterThan(40)
})

test('THE RACE: data pushed BEFORE the iframe loads is replayed (not lost)', async () => {
  // This is the real-app failure: Python pushes data right after creating the
  // figure, before the iframe has loaded its message listener. The state must
  // be buffered and replayed on iframe load — otherwise the image stays black.
  for (const s of replayState.states) {
    await inject({ type: 'state_update', fig_id: 'replay', key: s.key, value: s.value })
  }
  // Figure (and its iframe) arrives AFTER the data.
  await inject({
    type: 'figure', window_id: 2, fig_id: 'replay',
    html: placeholderHtml, title: 'Replay', is_navigator: false,
  })
  const { max } = await canvasStats(40)
  expect(max).toBeGreaterThan(40)
})
