"""
dpc.py — the DPC (differential phase contrast) physics: beam shifts → a field.

Pure compute. No Qt, no IPC, no ``Session`` — so ``spyde.api``, a notebook and
the :mod:`spyde.actions.dpc_action` wizard all run the SAME code (the host
parity contract in ``spyde/actions/README.md``). The interactive wiring lives in
``dpc_action.py``; the figures in ``dpc_display.py``.

The pipeline, in the order the wizard walks it:

1. **Measure** — :func:`measure_beam_shifts` wraps pyxem's
   ``get_direct_beam_position``: one (x, y) beam position per scan point.
2. **Center** — remove the part of that field which is NOT the sample: a
   constant (:func:`constant_reference`), a vacuum scan
   (:func:`vacuum_reference`), or a plane fitted through the four scan corners
   (:func:`corner_reference`). :func:`centering_report` says whether there is
   anything left to remove at all.
3. **Orient** — :func:`rotate_shifts` puts the detector's x/y onto the scan's
   x/y; :func:`estimate_rotation` finds that angle from the data.
4. **Calibrate** — magnetic DPC stops at the deflection; electric DPC goes on
   to MV/cm through :func:`to_electric_field`.
5. **Display** — :func:`magnitude_phase_rgb` and :func:`color_wheel_rgba`.

Two conventions are load-bearing and were both verified against pyxem 0.21
rather than assumed.

**Sign.** ``get_direct_beam_position`` returns ``centre − beam``: the shift you
would APPLY to centre the pattern, i.e. the NEGATIVE of the physical beam
deflection. Every pyxem DPC example (electric_field_dpc, magnetic_dpc) feeds
that value straight into ``get_magnitude_phase_signal`` /
``calibrate_electric_shifts``, so SpyDE does too — a map here matches a
published pyxem figure. ``calibrate_electric_shifts`` divides by ``-e``, which
puts the electric field back the right way round. Do not "fix" the sign here.

**Phase.** pyxem's phase is ``arctan2(shift_x, shift_y)`` — x against y, not the
usual y against x — with a −30° hue offset baked in. The colour wheel therefore
has to be rotated +90° relative to the map for its directions to read true in
the image, which is what ``plot_beam_shift_color`` does (``+60 = −30 + 90``) and
what the marker ``get_magnitude_phase_signal(add_color_wheel_marker=True)``
embeds does NOT (it reuses ``−30``, so it is 90° out and points the wrong way).

:func:`color_wheel_rgba` sidesteps that entirely: instead of porting a magic
offset, it evaluates :func:`magnitude_phase_rgb` — the very function that
colours the map — on a synthetic field of KNOWN screen directions. The legend is
generated by the map's own colour rule, so the two cannot drift apart. See
``test_dpc.py::TestPhaseConvention``.
"""
from __future__ import annotations

import logging
from dataclasses import dataclass, field as _dc_field

import numpy as np

log = logging.getLogger(__name__)

#: How the descan / zero-beam reference is obtained. The wizard's Center tab.
CENTER_MODES: tuple[str, ...] = ("none", "manual", "vacuum", "corners")

#: What the shifts are interpreted as. Magnetic stops at the deflection;
#: electric converts to MV/cm (and needs thickness + beam energy).
FIELD_MODES: tuple[str, ...] = ("magnetic", "electric")

#: ``get_direct_beam_position`` methods worth exposing.
BEAM_METHODS: tuple[str, ...] = ("center_of_mass", "blur", "interpolate",
                                 "cross_correlate")

#: Default corner-box size as a fraction of each scan axis (pyxem's own default
#: for ``get_linear_plane(fit_corners=…)``).
DEFAULT_CORNER_FRACTION = 0.05

#: Smallest corner block, per side, regardless of the fraction — see
#: :func:`corner_slices`.
MIN_CORNER_PX = 2

#: The hue offset used to paint a DPC map, and therefore also its colour wheel.
#:
#: ``None`` — i.e. pyxem's own −30° default — and it is a CONSTANT on purpose.
#: The scan↔detector rotation is applied to the shift VECTORS
#: (:func:`rotate_shifts`) before the field is coloured, so by the time
#: :func:`magnitude_phase_rgb` sees it the data is already in the scan frame and
#: needs no further hue turn. Feeding the scan rotation in here as well would
#: apply it twice, and the legend would then disagree with the map by exactly
#: that angle — a wrong-direction figure that still looks entirely plausible.
#: Because it is constant, the colour wheel is built ONCE and never has to
#: track anything. See ``test_dpc.py::TestDisplayRotation``.
DISPLAY_ROTATION: float | None = None

#: A scan whose residual descan is below this (px) is treated as already
#: centered — see :func:`centering_report`.
CENTERED_TOL_PX = 0.25

#: "argument not supplied", distinct from an explicit ``None``. Needed because
#: ``reference=None`` is a MEANINGFUL value — "there is no reference" — which
#: must not be confused with "derive one for me" (see :func:`compute_dpc`).
_UNSET: object = object()


# ─────────────────────────────────────────────────────────────────────────────
# 1. Measure
# ─────────────────────────────────────────────────────────────────────────────

#: Shapes the beam region can take. ``off`` searches the whole frame.
BEAM_SHAPES: tuple[str, ...] = ("circle", "ring")


@dataclass
class BeamRegion:
    """Where the direct beam is, as a shape the user drags onto it.

    It answers BOTH questions the Center step asks, which is why it is one
    object and one widget rather than two:

    * **which pixels the centre of mass integrates** (:meth:`mask`) — a
      diffracted disc inside the search area pulls the centroid towards itself,
      and on a strongly diffracting sample that drag is larger than the field
      being measured;
    * **where the undeflected beam is** (:attr:`center`) — the constant the
      Manual reference subtracts.

    ``ring`` exists for a beam-stopped or saturated direct beam: the core
    carries no usable intensity gradient (or none at all), so the centroid is
    taken over an annulus that captures the disc EDGE instead. The edge is
    symmetric about the true centre, so its centroid is still the beam position.

    Geometry is IMAGE PIXELS on the detector — the frame anyplotlib's 2-D
    widgets report and the frame ``measure_beam_shifts`` works in. Do not add a
    scale conversion.
    """
    shape: str = "circle"
    cx: float = 0.0
    cy: float = 0.0
    r: float = 0.0
    r_inner: float = 0.0

    @property
    def center(self) -> tuple[float, float]:
        return (float(self.cx), float(self.cy))

    @property
    def active(self) -> bool:
        """Whether this region can actually be integrated over.

        There is no "off" shape — the region is always on the pattern. What this
        still guards is the moment BEFORE a radius exists: a sensible default is
        a fraction of the detector, whose size is unknown until a dataset is
        open, so a freshly constructed region carries ``r = 0`` until
        :func:`default_beam_region` fills it in.
        """
        return self.shape in BEAM_SHAPES and self.r > 0

    def mask(self, sig_shape: tuple[int, int]) -> np.ndarray | None:
        """Boolean keep-mask over the detector, or ``None`` when inactive."""
        if not self.active:
            return None
        sy, sx = int(sig_shape[0]), int(sig_shape[1])
        yy, xx = np.mgrid[0:sy, 0:sx]
        rr = np.hypot(xx - float(self.cx), yy - float(self.cy))
        keep = rr <= float(self.r)
        if self.shape == "ring":
            keep &= rr >= float(self.r_inner)
        return keep

    def contains(self, x: float, y: float) -> bool:
        """Is this detector position inside the region? (Always True when off.)"""
        if not self.active:
            return True
        rr = float(np.hypot(float(x) - self.cx, float(y) - self.cy))
        if rr > float(self.r):
            return False
        return self.shape != "ring" or rr >= float(self.r_inner)

    def as_dict(self) -> dict:
        return {"shape": self.shape, "cx": float(self.cx), "cy": float(self.cy),
                "r": float(self.r), "r_inner": float(self.r_inner)}

    @classmethod
    def from_dict(cls, d: dict | None) -> "BeamRegion":
        d = d or {}
        shape = str(d.get("shape", "off"))
        return cls(shape=shape if shape in BEAM_SHAPES else "circle",
                   cx=float(d.get("cx") or 0.0), cy=float(d.get("cy") or 0.0),
                   r=float(d.get("r") or 0.0),
                   r_inner=float(d.get("r_inner") or 0.0))


def default_beam_region(sig_shape: tuple[int, int], shape: str = "circle"
                        ) -> BeamRegion:
    """The LARGEST region that fits on the detector — the inscribed circle.

    The region is always on the pattern, so its default is what every scan is
    measured with until someone drags it. That makes "generous" a correctness
    requirement, not a nicety: a region that CLIPS the beam pulls the centroid
    back towards its own centre and under-reads the shift. Measured on the
    synthetic disc, with the region centred on the frame:

    ======================  ==========================================
    radius                  error on a true shift of 1.5 / 3.0 / 4.5 px
    ======================  ==========================================
    ``0.25 * min(sy, sx)``  −0.30 / −1.00 / −1.76 px
    ``0.375 * min(sy, sx)`` −0.00 / −0.00 / −0.02 px
    ``0.5 * min(sy, sx)``   0 / 0 / 0
    ======================  ==========================================

    So a quarter-frame default — chosen when the region opened OFF and only
    ever appeared because someone asked for it — silently under-reads every
    field by up to 40%. The inscribed circle reproduces the whole-frame answer
    exactly, and shrinking it onto the beam (which is what excludes the
    first-order discs) is then a deliberate act with a readout to judge it by.
    """
    sy, sx = int(sig_shape[0]), int(sig_shape[1])
    r = max(2.0, 0.5 * min(sy, sx))
    return BeamRegion(shape=shape, cx=sx / 2.0, cy=sy / 2.0, r=r,
                      r_inner=r * 0.35)


def _com_shift_frame(frame, keep, cx0: float, cy0: float):
    """One frame's ``centre − beam`` shift, over the kept pixels.

    Deliberately the same arithmetic as pyxem's ``center_of_mass_from_image``
    (multiply by the mask, then ``ndi.center_of_mass``, then x/y order), so a
    circular region here and pyxem's own ``mask=(x, y, r)`` agree exactly —
    ``test_dpc.py::TestBeamRegion`` asserts that rather than trusting it.
    """
    from scipy import ndimage as ndi
    z = np.asarray(frame, dtype=np.float64)
    if keep is not None:
        z = z * keep
    total = z.sum()
    if not np.isfinite(total) or total <= 0:
        # Nothing inside the region — a NaN says "no measurement here" and
        # propagates visibly, where a silent 0 would read as a centred beam.
        return np.array([np.nan, np.nan], dtype=np.float64)
    com_y, com_x = ndi.center_of_mass(z)
    return np.array([cx0 - com_x, cy0 - com_y], dtype=np.float64)


def _region_weights(keep, sig_shape: tuple[int, int]) -> np.ndarray:
    """``(3, sy, sx)`` float64: the mask, and the mask weighted by x and by y.

    STACKED, so the centre of mass is one contraction over the data rather than
    three. All three quantities read the same block, and a block is the big
    thing — three separate ``einsum`` calls read it three times, which measured
    73 ms against 38 ms for the stacked form on a 64x64x64x64 scan.

    Built ONCE per pass, never per frame. They are detector-sized (a few hundred
    KB at most), while the data they weight is the whole scan.
    """
    sy, sx = int(sig_shape[0]), int(sig_shape[1])
    mask = (np.ones((sy, sx), dtype=np.float64) if keep is None
            else np.asarray(keep, dtype=np.float64))
    yy, xx = np.mgrid[0:sy, 0:sx].astype(np.float64)
    return np.stack([mask, mask * xx, mask * yy])


def _com_shift_blocks(block, weights, cx0: float, cy0: float) -> np.ndarray:
    """Every frame in a block's ``centre − beam`` shift → ``(..., 2)``.

    The vectorised twin of :func:`_com_shift_frame`, and the one production
    uses. Same arithmetic, same result — ``test_dpc.py`` asserts they agree
    element for element — but as three ``einsum`` contractions over the whole
    block instead of a Python call per frame with a ``scipy`` call inside it.
    A scan is tens of thousands of frames, so per-frame overhead IS the runtime;
    this is the same shape ``virtual_image`` reduces with, for the same reason.

    ``einsum`` also accumulates IN PLACE against detector-sized weights, so a
    block's only intermediates are the nav-sized outputs. Casting the block to
    float64 first would allocate four times the chunk on uint16 data — the
    "spills GiBs" pathology virtual_image documents.

    Do NOT pass ``optimize=True``: it plans a contraction that materialises an
    intermediate and measured 136 ms against 38 ms for the plain call.
    """
    moments = np.einsum("...ij,kij->...k", block, weights)
    total = moments[..., 0]
    # Nothing inside the region — a NaN says "no measurement here" and
    # propagates visibly, where a silent 0 would read as a centred beam.
    empty = ~np.isfinite(total) | (total <= 0)
    with np.errstate(invalid="ignore", divide="ignore"):
        out = np.stack([cx0 - moments[..., 1] / total,
                        cy0 - moments[..., 2] / total], axis=-1)
    out[empty] = np.nan
    return out


def private_view(signal):
    """A signal object the caller owns exclusively, over the SAME data buffer.

    hyperspy mutates the signal a method is called on. ``map`` — which every
    measure here goes through — reaches ``_deepcopy_with_new_data``, and that
    helper sets ``self.data = None`` on the LIVE object before deep-copying the
    wrapper, restoring it in a ``finally``. hyperspy's data setter turns that
    ``None`` into a length-1 OBJECT array, so for the width of the copy the
    signal publicly has ``data.shape == (1,)`` (``learning_results``, ``_plot``
    and the models dict are unset over the same window).

    Two threads calling ``map`` on ONE signal therefore race: the second reads
    the first's placeholder and dies with ``ValueError: Chunks do not add up to
    shape. Got chunks=((3, 3, -1, -1),), shape=(1,)``. It is a genuine race, not
    a rare one — it reproduces on a 4-core runner and hides on a many-core box,
    because the interleaving is what changes, not the code.

    **A superseded measure is CANCELLED, not left to finish** — see
    ``DpcWizard._cancel_measure``, which follows the same contract as
    ``virtual_image`` (cancel the prior future, unregister it, register the new
    one so closing the tree stops it). This view is not a licence to let stale
    passes run; it exists because cancellation cannot be instantaneous. A queued
    future cancels cleanly, but one already inside ``map`` runs to its end
    (``ComputeBackend.submit_graph`` documents the same contract), so the new
    pass can still overlap the tail of the old one. It also keeps the worker's
    ``set_signal_type`` off the tree's signal.

    Only the wrapper is duplicated — ``data`` is the same object, not a copy —
    so this stays cheap on a multi-GB lazy scan.

    Call it on the DISPATCH thread, before handing the result to a worker: the
    copy is itself a ``_deepcopy_with_new_data``, so it must not overlap another
    operation on the signal it is copying.
    """
    try:
        return signal._deepcopy_with_new_data(signal.data)
    except Exception as e:
        # Worse to refuse to measure than to measure on the shared object.
        log.debug("private signal view failed (%s); using the live signal", e)
        return signal


def beam_shift_graph(signal, *, method: str = "center_of_mass",
                     half_square_width: int = 0,
                     region: "BeamRegion | None" = None):
    """The LAZY ``(ny, nx, 2)`` beam-shift array, or ``None`` on eager data.

    Split out from :func:`measure_beam_shifts` so an interactive caller can hand
    the graph to ``client.compute`` and hold a CANCELLABLE future, instead of
    blocking on a pass a newer beam region has already superseded.
    The nav chunking is preserved end to end (no rechunk layer), which is what
    makes per-nav-chunk streaming line up with the storage — see Live-Display §1
    in CLAUDE.md and ``test_dpc.py::TestLazy``.
    """
    if not getattr(signal, "_lazy", False):
        return None
    try:
        signal.set_signal_type("electron_diffraction")
    except Exception as e:                                   # pragma: no cover
        log.debug("set_signal_type(electron_diffraction) failed: %s", e)
    if region is not None and region.active and str(method) == "center_of_mass":
        import dask.array as da
        sy, sx = _sig_shape(signal)
        data = signal.data
        weights = _region_weights(region.mask((sy, sx)), (sy, sx))
        # map_blocks, not hyperspy `map`: one vectorised contraction per chunk
        # rather than a Python call per frame. The nav chunking is preserved
        # (no rechunk layer), which is what keeps per-nav-chunk streaming lined
        # up with the storage — Live-Display §1.
        return da.map_blocks(
            _com_shift_blocks, data, weights=weights,
            cx0=sx / 2.0, cy0=sy / 2.0, dtype=np.float64,
            drop_axis=(data.ndim - 2, data.ndim - 1),
            new_axis=data.ndim - 2,
            chunks=data.chunks[:-2] + ((2,),),
            # Declared, not probed: without it dask calls the kernel an extra
            # time on a zero-sized block just to learn the output type.
            meta=np.empty((0,) * (data.ndim - 1), dtype=np.float64),
        )
    else:
        kw: dict = {"method": str(method), "lazy_output": True}
        hw = int(half_square_width or 0)
        if hw > 0:
            kw["half_square_width"] = hw
        out = signal.get_direct_beam_position(**kw)
    data = getattr(out, "data", None)
    return data if hasattr(data, "chunks") else None


def measure_beam_shifts(signal, *, method: str = "center_of_mass",
                        half_square_width: int = 0,
                        region: "BeamRegion | None" = None) -> np.ndarray:
    """Direct-beam position per scan point → ``(ny, nx, 2)`` float64, ``[x, y]``.

    pyxem's convention throughout: the value is ``centre − beam`` in detector
    PIXELS, ``[..., 0]`` horizontal (column) and ``[..., 1]`` vertical (row).

    *region* restricts the centre of mass to a disc or annulus the user has
    dragged onto the beam. pyxem's own ``mask=(x, y, r)`` covers the disc but
    rejects an array mask, so BOTH shapes go through :func:`_com_shift_frame`
    here — one code path, proven equal to pyxem's for the disc case, rather than
    two that could drift.

    *half_square_width* is pyxem's centred square, kept for the methods a region
    does not apply to (0 = whole frame; the kwarg is omitted rather than passed
    as 0, which pyxem reads as an empty window). A *region* supersedes it.

    This is a REDUCTION over the dataset, not a materialisation: a lazy signal
    streams through ``map`` and only the ``(ny, nx, 2)`` result is computed —
    the memory-safety rule in CLAUDE.md is respected.

    """
    try:
        signal.set_signal_type("electron_diffraction")
    except Exception as e:                                   # pragma: no cover
        log.debug("set_signal_type(electron_diffraction) failed: %s", e)

    if region is not None and region.active and str(method) == "center_of_mass":
        sig_shape = _sig_shape(signal)
        sy, sx = sig_shape
        weights = _region_weights(region.mask(sig_shape), sig_shape)
        # Straight through the vectorised path — hyperspy's `map` would add a
        # Python call per frame around arithmetic that is already one einsum
        # over the whole array.
        #
        # A LAZY signal goes through `beam_shift_graph` rather than contracting
        # the dask array here: this kernel's subscript is a per-BLOCK one, and
        # dask's own einsum does not reproduce it. One code path for lazy data,
        # and this function's contract stays a materialised (ny, nx, 2).
        graph = beam_shift_graph(signal, method=method,
                                 half_square_width=half_square_width,
                                 region=region)
        if graph is not None:
            return np.asarray(graph.compute(), dtype=np.float64)
        return _com_shift_blocks(signal.data, weights, sx / 2.0, sy / 2.0)
    else:
        kw: dict = {"method": str(method), "lazy_output": False}
        hw = int(half_square_width or 0)
        if hw > 0:
            kw["half_square_width"] = hw
        shifts = signal.get_direct_beam_position(**kw)
    if getattr(shifts, "_lazy", False):
        shifts.compute()
    return np.asarray(shifts.data, dtype=np.float64)


def region_brightness(signal, region: "BeamRegion | None", *, index=(0, 0)
                      ) -> float:
    """How many times brighter *region* is than the frame average — the live
    "am I on the beam?" readout while dragging.

    NOT the fraction of intensity captured, which was the obvious first choice
    and is unusable: that fraction depends on how much OTHER intensity the
    pattern carries, so a correctly-placed circle reads 0.7 on a weakly
    diffracting sample and 0.2 on a strongly diffracting one, and no single
    threshold means anything. Intensity DENSITY relative to the frame is
    scale-free: on the direct beam it is many times 1, off it is below 1.

    One frame, so it stays cheap enough to recompute on every drag settle. The
    authoritative check is :func:`beam_inside_region` after a real measure.
    """
    if region is None or not region.active:
        return float("inf")
    try:
        frame = np.asarray(signal.inav[int(index[1]), int(index[0])].data,
                           dtype=np.float64)
        keep = region.mask(frame.shape)
        n_in = int(keep.sum())
        if n_in == 0:
            return 0.0
        frame_mean = float(np.nanmean(frame))
        if not np.isfinite(frame_mean) or frame_mean <= 0:
            return 0.0
        return float(np.nansum(frame * keep) / n_in / frame_mean)
    except Exception as e:                                   # pragma: no cover
        log.debug("region brightness probe failed: %s", e)
        return float("inf")


#: A region dimmer than this multiple of the frame average is not on the beam.
#: 1.0 is "no brighter than average detector", which the direct beam never is.
BEAM_DIM_THRESHOLD = 1.0


def beam_inside_region(shifts: np.ndarray, region: "BeamRegion | None",
                       sig_shape: tuple[int, int]) -> bool:
    """Did the beam the measurement FOUND land inside the region?

    **This cannot catch a slipped CIRCLE, and it is important to know why.** The
    centroid of a non-negative distribution restricted to a CONVEX set always
    lies inside that set — so a disc anywhere on the detector trivially
    "contains" its own centroid, whether or not the beam is in it. Only a RING
    can fail this check, by putting the centroid in its hole, which is a real
    and useful signal that the ring is not concentric with the beam.

    For the "is it on the beam at all?" question use :func:`region_brightness`;
    the two together are what :func:`spyde.actions.dpc_action.DpcWizard.
    _warn_if_region_missed` reports on.
    """
    if region is None or not region.active:
        return True
    s = np.asarray(shifts, dtype=np.float64)
    finite = s[np.isfinite(s).all(axis=-1)]
    if finite.size == 0:
        return False
    sy, sx = int(sig_shape[0]), int(sig_shape[1])
    mean_shift = finite.reshape(-1, 2).mean(axis=0)
    # shift = centre - beam, so beam = centre - shift.
    return region.contains(sx / 2.0 - mean_shift[0], sy / 2.0 - mean_shift[1])


def as_beam_shift(shifts: np.ndarray, *, like=None, units: str = "px"):
    """Wrap an ``(ny, nx, 2)`` array back into a pyxem ``BeamShift``.

    Needed wherever pyxem's own physics is the authority (``get_linear_plane``,
    ``calibrate_electric_shifts``, ``get_magnitude_phase_signal``). *like* is an
    optional source signal whose navigation calibration and beam energy are
    copied across.
    """
    import pyxem as pxm
    bs = pxm.signals.BeamShift(np.asarray(shifts, dtype=np.float64))
    bs.units = [units, units]
    if like is not None:
        try:
            src_nav = like.axes_manager.navigation_axes
            for i, ax in enumerate(bs.axes_manager.navigation_axes):
                if i < len(src_nav):
                    ax.scale, ax.offset = src_nav[i].scale, src_nav[i].offset
                    ax.units, ax.name = src_nav[i].units, src_nav[i].name
        except Exception as e:                               # pragma: no cover
            log.debug("copying nav calibration onto BeamShift failed: %s", e)
        try:
            energy = beam_energy_kv(like)
            if energy is not None:
                bs.beam_energy = float(energy)
        except Exception as e:                               # pragma: no cover
            log.debug("copying beam energy onto BeamShift failed: %s", e)
    return bs


# ─────────────────────────────────────────────────────────────────────────────
# 2. Center — the descan / zero-beam reference
# ─────────────────────────────────────────────────────────────────────────────

def corner_slices(nav_shape: tuple[int, int],
                  corner_fraction: float = DEFAULT_CORNER_FRACTION
                  ) -> list[tuple[slice, slice]]:
    """The four corner blocks of a scan as ``(row_slice, col_slice)`` pairs.

    *nav_shape* is ``(ny, nx)`` — numpy order, matching ``shifts[..., 0].shape``.
    Each block spans ``corner_fraction`` of ITS OWN axis, so a 512 × 64 scan gets
    boxes that are wide and short rather than square.

    That last point is a deliberate divergence from pyxem's
    ``_get_corner_slices``, which derives both block sizes from
    ``navigation_axes[0]``/``[1]`` and then applies them to the numpy array in
    the opposite order — harmless on a square scan, transposed on any other. We
    build the mask ourselves and hand it to ``get_linear_plane(mask=…)`` instead
    of using ``fit_corners=…``, so the boxes the user SEES on the navigator are
    exactly the pixels the plane is fitted to (``test_dpc.py`` pins that).
    """
    ny, nx = int(nav_shape[0]), int(nav_shape[1])
    frac = float(np.clip(corner_fraction, 1e-6, 0.5))
    # Floor each side at MIN_CORNER_PX. Two planes of three parameters need 6
    # points; 1x1 boxes give exactly 4, so the fit is under-determined and the
    # blocks are invisible on screen besides. On a 256-wide scan the default 5%
    # is 13 px and the floor never binds — it exists for the small scans where
    # a fraction alone degenerates.
    hy = int(max(MIN_CORNER_PX, min(ny, round(ny * frac))))
    hx = int(max(MIN_CORNER_PX, min(nx, round(nx * frac))))
    top, bottom = slice(0, hy), slice(ny - hy, ny)
    left, right = slice(0, hx), slice(nx - hx, nx)
    return [(top, left), (top, right), (bottom, left), (bottom, right)]


def corner_boxes(nav_shape: tuple[int, int],
                 corner_fraction: float = DEFAULT_CORNER_FRACTION
                 ) -> list[tuple[float, float, float, float]]:
    """The same four blocks as drawable ``(x, y, w, h)`` rectangles.

    IMAGE PIXELS, the frame anyplotlib's 2-D widgets and markers use (see
    ``drift_action`` — do not add a scale conversion). Same source as
    :func:`corner_slices`, so the overlay cannot disagree with the fit.
    """
    out = []
    for rs, cs in corner_slices(nav_shape, corner_fraction):
        out.append((float(cs.start), float(rs.start),
                    float(cs.stop - cs.start), float(rs.stop - rs.start)))
    return out


def corner_mask(nav_shape: tuple[int, int],
                corner_fraction: float = DEFAULT_CORNER_FRACTION) -> np.ndarray:
    """``get_linear_plane``-style mask: ``True`` where the fit must IGNORE.

    So it is ``True`` everywhere except inside the four corner blocks.
    """
    mask = np.ones((int(nav_shape[0]), int(nav_shape[1])), dtype=bool)
    for rs, cs in corner_slices(nav_shape, corner_fraction):
        mask[rs, cs] = False
    return mask


def _fit_plane(values: np.ndarray, mask: np.ndarray | None) -> np.ndarray:
    """Least-squares plane ``a·col + b·row + c`` through the UNMASKED points.

    *mask* is ``True`` = ignore (pyxem's polarity). Falls back to the masked
    mean, then to zeros, when the selected points can't determine a plane
    (fewer than 3, or all collinear) — a flat reference is a defensible
    reference; a singular-matrix traceback in the middle of a wizard is not.
    """
    ny, nx = values.shape
    rows, cols = np.mgrid[0:ny, 0:nx]
    keep = np.isfinite(values)
    if mask is not None:
        keep &= ~mask
    n = int(keep.sum())
    if n == 0:
        return np.zeros_like(values, dtype=np.float64)
    A = np.stack([cols[keep].ravel(), rows[keep].ravel(),
                  np.ones(n)], axis=1).astype(np.float64)
    b = values[keep].ravel().astype(np.float64)
    if n < 3:
        return np.full_like(values, float(b.mean()), dtype=np.float64)
    try:
        coef, *_ = np.linalg.lstsq(A, b, rcond=None)
    except np.linalg.LinAlgError:                            # pragma: no cover
        return np.full_like(values, float(b.mean()), dtype=np.float64)
    if not np.all(np.isfinite(coef)):                        # pragma: no cover
        return np.full_like(values, float(b.mean()), dtype=np.float64)
    return (coef[0] * cols + coef[1] * rows + coef[2]).astype(np.float64)


def plane_through(shifts: np.ndarray, mask: np.ndarray | None) -> np.ndarray:
    """Fit an independent plane to each of the x- and y-shift components."""
    shifts = np.asarray(shifts, dtype=np.float64)
    return np.stack([_fit_plane(shifts[..., 0], mask),
                     _fit_plane(shifts[..., 1], mask)], axis=-1)


def corner_reference(shifts: np.ndarray,
                     corner_fraction: float = DEFAULT_CORNER_FRACTION
                     ) -> np.ndarray:
    """Descan reference from the four scan corners.

    The corners are assumed to be off the feature of interest, so whatever beam
    shift they carry is instrument descan. A plane through them extrapolates
    that ramp across the whole scan — pyxem's ``get_linear_plane(fit_corners=…)``
    idea, with the boxes made visible and made correct on non-square scans (see
    :func:`corner_slices`).
    """
    nav_shape = np.asarray(shifts).shape[:2]
    return plane_through(shifts, corner_mask(nav_shape, corner_fraction))


def constant_reference(nav_shape: tuple[int, int], center_xy, sig_shape
                       ) -> np.ndarray:
    """Descan reference from ONE hand-picked beam position (the Manual tab).

    *center_xy* is the picked ``(x, y)`` in detector pixels; *sig_shape* is
    ``(sy, sx)``. The result is the constant ``centre − picked``, broadcast over
    the scan — the same value and the same sign convention
    ``get_direct_beam_position`` would have produced if the beam sat exactly
    there in every pattern.
    """
    sy, sx = int(sig_shape[0]), int(sig_shape[1])
    ref = np.zeros((int(nav_shape[0]), int(nav_shape[1]), 2), dtype=np.float64)
    ref[..., 0] = sx / 2.0 - float(center_xy[0])
    ref[..., 1] = sy / 2.0 - float(center_xy[1])
    return ref


def vacuum_reference(shifts: np.ndarray, vacuum_shifts: np.ndarray, *,
                     smooth: bool = True) -> np.ndarray:
    """Descan reference from a VACUUM scan taken with the same scan settings.

    The gold standard: the vacuum scan contains only the instrument's descan, so
    it is subtracted point for point.

    *smooth* (the default) reduces the vacuum field to its own fitted plane
    first, which is usually what you want — it keeps the vacuum scan's shot
    noise out of the sample's field, and the descan being corrected for really
    is a plane. Set it False to subtract the vacuum scan verbatim.

    **A differently-shaped vacuum scan is assumed to cover the SAME FIELD OF
    VIEW at a different sampling density** — the plane is re-evaluated on the
    sample's grid in normalised corner-to-corner coordinates. That is the real
    case this handles (a quick coarse vacuum scan before a fine sample scan),
    but it is an assumption the array shapes cannot confirm: a vacuum scan of a
    DIFFERENT field of view gets its ramp stretched or squashed to fit, and the
    result is wrong in a way that still looks plausible. The caller is expected
    to say so — ``dpc_action`` warns in the status line whenever the shapes
    differ. Matching shapes need no such assumption and are always preferred.
    """
    shifts = np.asarray(shifts, dtype=np.float64)
    vac = np.asarray(vacuum_shifts, dtype=np.float64)
    if vac.ndim != 3 or vac.shape[-1] != 2:
        raise ValueError(
            f"vacuum reference must be an (ny, nx, 2) beam-shift field, got "
            f"{vac.shape}")
    if vac.shape[:2] == shifts.shape[:2] and not smooth:
        return vac
    plane = plane_through(vac, None)
    if plane.shape[:2] == shifts.shape[:2]:
        return plane
    return _resample_plane(plane, shifts.shape[:2])


def _resample_plane(plane: np.ndarray, nav_shape: tuple[int, int]) -> np.ndarray:
    """Re-evaluate a fitted plane on a different-sized scan grid.

    A plane is fully described by its corners, so bilinear interpolation between
    them is exact — no scipy, no resampling artefacts.
    """
    ny, nx = int(nav_shape[0]), int(nav_shape[1])
    sy, sx = plane.shape[0], plane.shape[1]
    v = np.linspace(0.0, 1.0, ny)[:, None]
    u = np.linspace(0.0, 1.0, nx)[None, :]
    out = np.empty((ny, nx, 2), dtype=np.float64)
    for c in (0, 1):
        p = plane[..., c]
        tl, tr = p[0, 0], p[0, sx - 1]
        bl, br = p[sy - 1, 0], p[sy - 1, sx - 1]
        out[..., c] = (tl * (1 - u) * (1 - v) + tr * u * (1 - v)
                       + bl * (1 - u) * v + br * u * v)
    return out


@dataclass
class CenteringReport:
    """What is left of the beam-shift field once the sample signal is set aside.

    ``offset`` is the scan-mean shift (a constant descan) and ``ramp`` the
    peak-to-peak of the fitted plane across the scan (a descan gradient), both
    in detector pixels as ``(x, y)``. :attr:`centered` is the wizard's
    "there is nothing to correct here, skip this step" verdict.
    """
    offset: tuple[float, float]
    ramp: tuple[float, float]
    tol_px: float

    @property
    def worst(self) -> float:
        return float(max(max(abs(v) for v in self.offset),
                         max(abs(v) for v in self.ramp)))

    @property
    def centered(self) -> bool:
        return self.worst <= self.tol_px

    def as_dict(self) -> dict:
        return {"offset": list(self.offset), "ramp": list(self.ramp),
                "worst": self.worst, "centered": self.centered,
                "tol_px": self.tol_px}


def centering_report(shifts: np.ndarray, *, tol_px: float = CENTERED_TOL_PX
                     ) -> CenteringReport:
    """Measure the residual descan so the Center step can be skipped honestly.

    Both parts matter and neither alone is enough: a scan can be perfectly
    centred on average while carrying a large ramp, and it can have zero ramp
    while sitting a long way off centre. A dataset that is already centered
    (e.g. Center Zero Beam has run, or the microscope descan was good) shows
    small values for both, and the wizard says so instead of making the user
    guess.
    """
    shifts = np.asarray(shifts, dtype=np.float64)
    plane = plane_through(shifts, None)
    offs, ramps = [], []
    for c in (0, 1):
        v = shifts[..., c]
        finite = v[np.isfinite(v)]
        offs.append(float(finite.mean()) if finite.size else 0.0)
        p = plane[..., c]
        ramps.append(float(np.nanmax(p) - np.nanmin(p)) if p.size else 0.0)
    return CenteringReport(offset=(offs[0], offs[1]),
                           ramp=(ramps[0], ramps[1]), tol_px=float(tol_px))


def resolve_reference(shifts: np.ndarray, *, center_mode: str,
                      corner_fraction: float = DEFAULT_CORNER_FRACTION,
                      center_xy=None, vacuum_shifts: np.ndarray | None = None,
                      sig_shape: tuple[int, int] | None = None,
                      strict: bool = True) -> np.ndarray | None:
    """Build the descan reference *center_mode* asks for.

    The single place the Center tab's four modes turn into an array, shared by
    :func:`compute_dpc` and the wizard so the two cannot disagree about what
    "corners" means.

    *strict* controls what a missing input does. Scripting (the default) gets a
    ``ValueError`` naming the argument it needs; the wizard passes
    ``strict=False``, because a caret sitting on Manual with no crosshair placed
    yet is mid-interaction, not misconfigured, and "no reference yet" renders
    perfectly well.
    """
    if center_mode not in CENTER_MODES:
        raise ValueError(f"center_mode must be one of {CENTER_MODES}, "
                         f"got {center_mode!r}")
    shifts = np.asarray(shifts, dtype=np.float64)
    if center_mode == "none":
        return None
    if center_mode == "corners":
        return corner_reference(shifts, corner_fraction)
    if center_mode == "manual":
        if center_xy is None or center_xy[0] is None or center_xy[1] is None:
            if strict:
                raise ValueError("center_mode='manual' needs center_xy=(x, y)")
            return None
        if sig_shape is None:
            raise ValueError("center_mode='manual' needs the signal shape")
        return constant_reference(shifts.shape[:2], center_xy, sig_shape)
    if center_mode == "vacuum":
        if vacuum_shifts is None:
            if strict:
                raise ValueError("center_mode='vacuum' needs vacuum_shifts")
            return None
        return vacuum_reference(shifts, vacuum_shifts)
    return None


def _sig_shape(signal) -> tuple[int, int] | None:
    """``(sy, sx)`` of the detector, or ``None`` for a signal without one."""
    try:
        ax = signal.axes_manager.signal_axes
        return (int(ax[1].size), int(ax[0].size))
    except Exception:                                        # pragma: no cover
        return None


def apply_reference(shifts: np.ndarray, reference: np.ndarray | None
                    ) -> np.ndarray:
    """``shifts − reference`` (a ``None`` reference is the identity)."""
    shifts = np.asarray(shifts, dtype=np.float64)
    if reference is None:
        return shifts.copy()
    ref = np.asarray(reference, dtype=np.float64)
    if ref.shape != shifts.shape:
        raise ValueError(f"reference {ref.shape} does not match shifts "
                         f"{shifts.shape}")
    return shifts - ref


# ─────────────────────────────────────────────────────────────────────────────
# 3. Orient — detector x/y onto scan x/y
# ─────────────────────────────────────────────────────────────────────────────

def rotate_shifts(shifts: np.ndarray, angle_deg: float, *,
                  flip: bool = False, reverse: bool = False) -> np.ndarray:
    """Put the beam-shift vectors into the scan frame.

    Three corrections, applied in this order, because that is the order the
    instrument applies them in reverse:

    *flip* swaps the x and y components — a HANDEDNESS change, for when the scan
    coils and the detector read out with opposite chirality. It has to come
    first: a mirror does not commute with a rotation, and doing it afterwards
    silently negates the fitted angle.

    *angle_deg* rotates the vectors CLOCKWISE, matching pyxem's
    ``rotate_beam_shifts`` exactly (same formula, so a SpyDE angle and a pyxem
    angle mean the same thing).

    *reverse* adds 180°, for the sign ambiguity :func:`estimate_rotation`
    cannot resolve on its own.
    """
    s = np.asarray(shifts, dtype=np.float64)
    sx, sy = s[..., 0], s[..., 1]
    if flip:
        sx, sy = sy, sx
    ang = np.deg2rad(float(angle_deg) + (180.0 if reverse else 0.0))
    c, sn = np.cos(ang), np.sin(ang)
    return np.stack([sx * c - sy * sn, sx * sn + sy * c], axis=-1)


def _div_curl(sx: np.ndarray, sy: np.ndarray,
              scale: tuple[float, float] = (1.0, 1.0)
              ) -> tuple[np.ndarray, np.ndarray]:
    """``(divergence, curl_z)`` of the in-plane field, in SCAN coordinates.

    Axis 0 of the arrays is the scan's y (rows), axis 1 its x (columns).
    *scale* is ``(dy, dx)`` in whatever calibrated unit the nav axes use; it
    cancels out of the rotation search (both terms scale together) but keeps the
    reported numbers physical.
    """
    dy, dx = float(scale[0]) or 1.0, float(scale[1]) or 1.0
    dsx_dy, dsx_dx = np.gradient(sx, dy, dx)
    dsy_dy, dsy_dx = np.gradient(sy, dy, dx)
    return dsx_dx + dsy_dy, dsy_dx - dsx_dy


def _rms(a: np.ndarray) -> float:
    finite = a[np.isfinite(a)]
    return float(np.sqrt(np.mean(finite ** 2))) if finite.size else 0.0


@dataclass
class RotationEstimate:
    """The result of :func:`estimate_rotation`."""
    angle: float                     #: best clockwise rotation, degrees
    flip: bool                       #: whether swapping x/y won
    mode: str                        #: "electric" (min curl) or "magnetic" (min div)
    score: float                     #: the minimised RMS at *angle*
    baseline: float                  #: the same RMS at 0°, no flip
    angles: np.ndarray = _dc_field(default_factory=lambda: np.empty(0))
    curve: np.ndarray = _dc_field(default_factory=lambda: np.empty(0))

    @property
    def improvement(self) -> float:
        """How many times smaller the residual got. 1.0 = the fit found nothing."""
        return float(self.baseline / self.score) if self.score > 0 else float("inf")

    def as_dict(self) -> dict:
        return {"angle": float(self.angle), "flip": bool(self.flip),
                "mode": self.mode, "score": float(self.score),
                "baseline": float(self.baseline),
                "improvement": float(min(self.improvement, 1e6))}


def estimate_rotation(shifts: np.ndarray, *, mode: str = "electric",
                      nav_scale: tuple[float, float] = (1.0, 1.0),
                      step_deg: float = 0.5) -> RotationEstimate:
    """Find the scan↔detector rotation (and handedness) from the data itself.

    The physics gives one constraint per mode:

    * **electric** — ``E = −∇V`` is a gradient field, so its curl vanishes.
    * **magnetic** — the Lorentz deflection is ``∝ B × ẑ``; with ``∇·B = 0`` in
      a uniform-thickness film the in-plane shift field is divergence-free.

    So the correct rotation is the one that drives the wrong-symmetry component
    to zero. The search is closed-form rather than brute force: rotating the
    vectors by θ takes ``(div, curl)`` to

        ``div(θ)  =  cos θ · div₀ − sin θ · curl₀``
        ``curl(θ) =  sin θ · div₀ + cos θ · curl₀``

    so ``div₀`` and ``curl₀`` are differentiated ONCE and the whole θ sweep is a
    pair of dot products. Both handedness options are evaluated and the better
    one returned.

    **180° is not resolvable this way** — both residuals are even under
    ``θ → θ + 180`` — which is why :func:`rotate_shifts` takes a separate
    ``reverse`` flag for the user to set from physical knowledge (which side of
    a p-n junction is positive, which way the domains point).
    """
    if mode not in FIELD_MODES:
        raise ValueError(f"mode must be one of {FIELD_MODES}, got {mode!r}")
    s = np.asarray(shifts, dtype=np.float64)
    angles = np.arange(0.0, 360.0, float(step_deg))
    rad = np.deg2rad(angles)
    cos_t, sin_t = np.cos(rad), np.sin(rad)

    best: RotationEstimate | None = None
    baseline = 0.0
    for flip in (False, True):
        sx, sy = (s[..., 1], s[..., 0]) if flip else (s[..., 0], s[..., 1])
        div0, curl0 = _div_curl(sx, sy, nav_scale)
        d0, c0 = div0.ravel(), curl0.ravel()
        good = np.isfinite(d0) & np.isfinite(c0)
        d0, c0 = d0[good], c0[good]
        if d0.size == 0:                                     # pragma: no cover
            continue
        # ⟨(a·d0 + b·c0)²⟩ expands to a²⟨d0²⟩ + 2ab⟨d0c0⟩ + b²⟨c0²⟩, so the
        # whole sweep needs three scalars — not one gradient per angle.
        dd, dc, cc = float(d0 @ d0), float(d0 @ c0), float(c0 @ c0)
        n = float(d0.size)
        if mode == "electric":            # minimise curl(θ)
            a, b = sin_t, cos_t
        else:                             # minimise div(θ)
            a, b = cos_t, -sin_t
        curve = np.sqrt(np.maximum(0.0, (a * a * dd + 2 * a * b * dc
                                         + b * b * cc) / n))
        if not flip:
            baseline = float(curve[0])
        i = int(np.argmin(curve))
        cand = RotationEstimate(angle=float(angles[i]), flip=flip, mode=mode,
                                score=float(curve[i]), baseline=baseline,
                                angles=angles, curve=curve)
        if best is None or cand.score < best.score:
            best = cand
    if best is None:                                         # pragma: no cover
        return RotationEstimate(angle=0.0, flip=False, mode=mode, score=0.0,
                                baseline=0.0, angles=angles,
                                curve=np.zeros_like(angles))
    best.baseline = baseline
    return best


def field_symmetry(shifts: np.ndarray,
                   nav_scale: tuple[float, float] = (1.0, 1.0)
                   ) -> tuple[float, float]:
    """``(rms_divergence, rms_curl)`` of a field — the rotation quality readout."""
    s = np.asarray(shifts, dtype=np.float64)
    div, curl = _div_curl(s[..., 0], s[..., 1], nav_scale)
    return _rms(div), _rms(curl)


# ─────────────────────────────────────────────────────────────────────────────
# 4. Calibrate
# ─────────────────────────────────────────────────────────────────────────────

def beam_energy_kv(signal) -> float | None:
    """Accelerating voltage in kV from the signal's metadata, or ``None``."""
    for getter in (
        lambda: signal.calibration.beam_energy,
        lambda: signal.metadata.Acquisition_instrument.TEM.beam_energy,
        lambda: signal.beam_energy,
    ):
        try:
            v = getter()
        except Exception:
            continue
        if v is not None and np.isfinite(float(v)) and float(v) > 0:
            return float(v)
    return None


def _wavelength_nm(beam_energy_kev: float) -> float:
    """Relativistic electron wavelength in nm."""
    from scipy.constants import c, e, h, m_e
    v = float(beam_energy_kev) * 1e3
    return (h / np.sqrt(2 * m_e * e * v * (1 + e * v / (2 * m_e * c ** 2)))) * 1e9


def mrad_per_pixel(signal) -> float | None:
    """Detector scale in mrad/pixel, or ``None`` if the data isn't calibrated.

    Accepts axes already in mrad, or reciprocal axes (nm⁻¹ / Å⁻¹) which are
    converted through ``θ = k·λ`` — the same relation pyxem's
    ``calibration.convert_signal_units("mrad")`` uses, done here directly so it
    also works on a signal whose ``calibration`` object was never set up.
    """
    try:
        ax = signal.axes_manager.signal_axes[0]
        scale, units = float(ax.scale), str(ax.units or "").strip()
    except Exception:                                        # pragma: no cover
        return None
    if not np.isfinite(scale) or scale <= 0:
        return None
    u = units.lower().replace(" ", "")
    if u in ("mrad", "milliradian", "milliradians"):
        return scale
    if u in ("rad", "radian", "radians"):
        return scale * 1e3
    energy = beam_energy_kv(signal)
    if energy is None:
        return None
    lam_nm = _wavelength_nm(energy)
    if u in ("nm^-1", "1/nm", "nm⁻¹", "nm-1"):
        return scale * lam_nm * 1e3
    if u in ("a^-1", "1/a", "å^-1", "1/å", "å⁻¹", "a-1", "angstrom^-1"):
        return scale * 10.0 * lam_nm * 1e3          # Å⁻¹ → nm⁻¹ is ×10
    return None


def to_electric_field(shifts_px: np.ndarray, *, mrad_per_px: float,
                      thickness_nm: float, beam_energy_kev: float,
                      like=None) -> np.ndarray:
    """Beam shifts in pixels → electric field in MV/cm.

    Delegates the physics to pyxem's ``calibrate_electric_shifts`` (the relation
    ``E = m₀·γ·|v|²·θ / (e·t)`` from the electric-field example) rather than
    re-deriving it, so the numbers match the reference workflow. All this adds
    is the pixels→mrad step, which pyxem normally reaches through a fully
    configured ``calibration`` object — doing it explicitly means an
    uncalibrated dataset still works once the user supplies the scale.
    """
    if not np.isfinite(mrad_per_px) or mrad_per_px <= 0:
        raise ValueError("mrad_per_px must be a positive, finite number")
    if not np.isfinite(thickness_nm) or thickness_nm <= 0:
        raise ValueError("thickness must be a positive number of nanometres")
    if not np.isfinite(beam_energy_kev) or beam_energy_kev <= 0:
        raise ValueError("beam energy must be a positive number of kV")
    bs = as_beam_shift(np.asarray(shifts_px, np.float64) * float(mrad_per_px),
                       like=like, units="mrad")
    bs.units = ["mrad", "mrad"]
    bs.beam_energy = float(beam_energy_kev)
    return np.asarray(bs.calibrate_electric_shifts(
        thickness=float(thickness_nm)).data, dtype=np.float64)


#: Display unit for each field mode, given the calibration that was available.
def field_units(mode: str, calibrated: bool) -> str:
    if mode == "electric":
        return "MV/cm" if calibrated else "px"
    return "mrad" if calibrated else "px"


# ─────────────────────────────────────────────────────────────────────────────
# 5. Display
# ─────────────────────────────────────────────────────────────────────────────

def magnitude_phase_rgb(shifts: np.ndarray, *, rotation: float | None = None,
                        autolim: bool = True, autolim_sigma: float = 4.0,
                        magnitude_limits: tuple[float, float] | None = None,
                        only_phase: bool = False) -> np.ndarray:
    """Beam shifts → an ``(ny, nx, 3)`` uint8 RGB map. Hue = direction, value =
    magnitude.

    This is pyxem's ``BeamShift.get_magnitude_phase_signal`` — called through
    the public method rather than reimplemented, so a SpyDE map is the same
    picture the pyxem examples produce, including the −30° hue offset it applies
    internally. ``add_color_wheel_marker=False``: that marker is a matplotlib
    artist SpyDE cannot render, and its rotation is 90° out anyway (see the
    module docstring) — :func:`color_wheel_rgba` builds the legend instead.

    *only_phase* drops the magnitude weighting so every pixel shows its
    direction at full saturation; useful where the field is weak but ordered.

    Non-finite positions render BLACK rather than poisoning the image. They are
    real and mean "no measurement here": a scan position still streaming in
    during a progressive fill, or one whose beam region captured nothing. Left
    in, a single NaN takes out the whole map, because ``autolim`` derives the
    magnitude limits from a mean and standard deviation.
    """
    bs = as_beam_shift(np.nan_to_num(np.asarray(shifts, dtype=np.float64),
                                     nan=0.0, posinf=0.0, neginf=0.0))
    kw: dict = {"rotation": rotation, "add_color_wheel_marker": False}
    if only_phase:
        s_rgb = bs.get_phase_signal(**kw)
    else:
        s_rgb = bs.get_magnitude_phase_signal(
            autolim=bool(autolim) and magnitude_limits is None,
            autolim_sigma=float(autolim_sigma),
            magnitude_limits=magnitude_limits, **kw)
    s_rgb.change_dtype("uint16")
    arr = np.asarray(s_rgb.data)
    if arr.ndim == 2:                                        # pragma: no cover
        arr = arr[..., None].repeat(3, axis=-1)
    return (arr[..., :3] >> 8).astype(np.uint8)


def magnitude_ceiling(field: np.ndarray, *, autolim_sigma: float = 4.0
                      ) -> float | None:
    """The field magnitude the colour wheel's RIM stands for, in the field's own
    units. The wheel's centre is 0, so this is the other end of its scale.

    :func:`magnitude_phase_rgb` lets pyxem's autolim choose the display ceiling,
    so the only number that cannot disagree with the picture is the one pyxem
    itself computed. This makes the same call on the same array — ``nan_to_num``
    first, exactly as the map does.

    ``None`` if pyxem's helper moves. A legend with no scale on it is a small
    loss; a legend with the WRONG scale on it is a wrong measurement, and it
    would be believed.
    """
    try:
        from pyxem.utils._beam_shift_tools import _get_limits_from_array
    except Exception as e:                                   # pragma: no cover
        log.debug("pyxem's magnitude-limit helper is not importable, so the "
                  "colour wheel goes without a scale: %s", e)
        return None
    try:
        clean = np.nan_to_num(np.asarray(field, dtype=np.float64),
                              nan=0.0, posinf=0.0, neginf=0.0)
        ceiling = float(_get_limits_from_array(
            magnitude(clean), sigma=float(autolim_sigma))[1])
    except Exception as e:                                   # pragma: no cover
        log.debug("deriving the colour-wheel scale failed: %s", e)
        return None
    return ceiling if np.isfinite(ceiling) and ceiling > 0 else None


def color_wheel_rgba(size: int = 192, *, rotation: float | None = None,
                     only_phase: bool = False) -> np.ndarray:
    """The circular phase-direction legend → ``(size, size, 4)`` uint8 RGBA.

    **Generated by the map's own colour rule, not by a copied offset.** The
    wheel is a synthetic beam-shift field in which the shift at each pixel
    points at that pixel's own SCREEN direction from the centre, run through
    :func:`magnitude_phase_rgb` with the same *rotation* as the map. So "find
    this colour on the wheel, read off which way it points" is correct by
    construction, and it stays correct if the colour rule ever changes.

    The screen frame is the displayed image's: ``+x`` right, ``+y`` DOWN (the
    map is drawn ``origin="upper"``). A pixel that sits to the upper-right of the
    wheel centre therefore carries the colour of a shift pointing up and to the
    right in the map.

    Magnitude ramps 0 → 1 from centre to rim, so the legend reads as a key for
    both quantities: black in the middle is zero field, the saturated rim is the
    display maximum. Outside the disc alpha is 0, and the rim is feathered over
    one pixel so it does not alias against the map underneath.
    """
    n = int(max(16, size))
    c = (n - 1) / 2.0
    rows, cols = np.mgrid[0:n, 0:n].astype(np.float64)
    u = (cols - c) / c                     # +right
    v = (rows - c) / c                     # +down  (origin="upper")
    r = np.hypot(u, v)
    # The shift at this pixel points the way the pixel lies: sx = right, sy = down.
    shifts = np.stack([u, v], axis=-1)
    rgb = magnitude_phase_rgb(shifts, rotation=rotation, autolim=False,
                              magnitude_limits=(0.0, 1.0), only_phase=only_phase)
    edge = 2.0 / n
    alpha = np.clip((1.0 - r) / edge, 0.0, 1.0)
    out = np.empty((n, n, 4), dtype=np.uint8)
    out[..., :3] = rgb
    out[..., 3] = (alpha * 255.0).astype(np.uint8)
    return out


def magnitude(shifts: np.ndarray) -> np.ndarray:
    """``|shift|`` per scan point."""
    s = np.asarray(shifts, dtype=np.float64)
    return np.hypot(s[..., 0], s[..., 1])


def phase(shifts: np.ndarray, *, rotation: float | None = None) -> np.ndarray:
    """Direction per scan point in RADIANS on ``[0, 2π)``.

    pyxem's ``arctan2(x, y)`` convention with its −30° display offset applied,
    i.e. the exact angle whose hue :func:`magnitude_phase_rgb` paints, so a
    committed phase map and the RGB map agree.
    """
    s = np.asarray(shifts, dtype=np.float64)
    rot = -30.0 if rotation is None else float(rotation) - 30.0
    return (np.arctan2(s[..., 0], s[..., 1]) + np.deg2rad(rot)) % (2 * np.pi)


# ─────────────────────────────────────────────────────────────────────────────
# The whole pipeline, for a script / notebook / the api layer
# ─────────────────────────────────────────────────────────────────────────────

@dataclass
class DpcResult:
    """Everything one DPC run produces, in one object.

    :attr:`field` is the oriented, calibrated field as ``(ny, nx, 2)``; the
    scalar maps are derived views of it. :attr:`units` says what
    :attr:`field` is in — ``MV/cm`` for a calibrated electric run, ``mrad``
    for a calibrated magnetic one, ``px`` when the dataset carried no
    detector calibration.
    """
    field: np.ndarray
    raw_shifts: np.ndarray
    reference: np.ndarray | None
    units: str
    mode: str
    rotation: float
    flip: bool
    reverse: bool
    rgb: np.ndarray
    wheel: np.ndarray
    centering: CenteringReport | None = None
    estimate: RotationEstimate | None = None
    params: dict = _dc_field(default_factory=dict)
    #: Set by ``spyde.api.dpc_map`` / the wizard's Commit — the same record
    #: shape ``commit._stamp_provenance`` writes.
    provenance: dict | None = None

    @property
    def fx(self) -> np.ndarray:
        """The x (horizontal / scan-column) component."""
        return self.field[..., 0]

    @property
    def fy(self) -> np.ndarray:
        """The y (vertical / scan-row) component."""
        return self.field[..., 1]

    @property
    def magnitude(self) -> np.ndarray:
        return magnitude(self.field)

    @property
    def phase(self) -> np.ndarray:
        return phase(self.field, rotation=DISPLAY_ROTATION)

    @property
    def divergence(self) -> np.ndarray:
        """``∇·F`` — charge density, up to a constant, for an electric field."""
        return _div_curl(self.field[..., 0], self.field[..., 1])[0]

    @property
    def curl(self) -> np.ndarray:
        """``(∇×F)_z`` — should be ~0 for a well-oriented electric field."""
        return _div_curl(self.field[..., 0], self.field[..., 1])[1]

    def component(self, name: str) -> np.ndarray:
        return {"fx": self.fx, "fy": self.fy, "magnitude": self.magnitude,
                "phase": self.phase, "divergence": self.divergence,
                "curl": self.curl}[name]


#: Scalar maps a DPC result can show, in the order the view chips list them.
COMPONENTS: tuple[str, ...] = ("fx", "fy", "magnitude", "phase", "divergence",
                               "curl")


def component_titles(mode: str, units: str) -> dict[str, str]:
    """Human labels for :data:`COMPONENTS`, named for the physics being mapped."""
    sym = "E" if mode == "electric" else "B"
    return {
        "fx": f"{sym}x ({units})", "fy": f"{sym}y ({units})",
        "magnitude": f"|{sym}| ({units})", "phase": "Direction (rad)",
        "divergence": "Divergence", "curl": "Curl",
    }
def compute_dpc(signal, *, mode: str = "magnetic",
                method: str = "center_of_mass", half_square_width: int = 0,
                center_mode: str = "corners",
                corner_fraction: float = DEFAULT_CORNER_FRACTION,
                center_xy: tuple[float, float] | None = None,
                vacuum_shifts: np.ndarray | None = None,
                rotation: float | None = None, flip: bool = False,
                reverse: bool = False, auto_rotation: bool = False,
                thickness_nm: float | None = None,
                beam_energy_kev: float | None = None,
                mrad_per_px: float | None = None,
                autolim_sigma: float = 4.0,
                region: "BeamRegion | None" = None,
                shifts: np.ndarray | None = None,
                reference: np.ndarray | None = _UNSET) -> DpcResult:
    """Run the whole DPC pipeline on *signal* and return a :class:`DpcResult`.

    The one entry point shared by ``spyde.api.dpc_map`` and the wizard's Run
    stage, so a scripted result and a clicked one cannot diverge. Pass
    pre-measured *shifts* to skip step 1 (the wizard does, because it measures
    once and then re-orients interactively).

    Pass an explicit *reference* to skip step 2's derivation as well. The wizard
    does that too, and not just for speed: its Center tab can sit in a mode whose
    reference is not determined YET (Manual before a crosshair has been placed,
    Vacuum before a dataset has been chosen). Deriving from *center_mode* alone
    would have to raise there, in the middle of an interaction where "no
    reference yet" is the honest and perfectly usable state. A caller who does
    supply *center_mode* without a reference is scripting, not interacting, and
    a missing input IS an error for them.
    """
    if mode not in FIELD_MODES:
        raise ValueError(f"mode must be one of {FIELD_MODES}, got {mode!r}")
    if center_mode not in CENTER_MODES:
        raise ValueError(f"center_mode must be one of {CENTER_MODES}, "
                         f"got {center_mode!r}")
    raw = (np.asarray(shifts, np.float64) if shifts is not None
           else measure_beam_shifts(signal, method=method,
                                    half_square_width=half_square_width,
                                    region=region))
    report = centering_report(raw)

    # A region dragged onto the beam already says where the beam is, so Manual
    # needs no separate pick — the region's centre IS the reference. This is the
    # whole point of one shape doing both jobs.
    if (center_mode == "manual" and center_xy is None
            and region is not None and region.active):
        center_xy = region.center
    # `is _UNSET`, not `is None` — an explicit `reference=None` means "the
    # caller has decided there is no reference", which is exactly the wizard's
    # not-picked-yet state and must NOT fall back to deriving one.
    if reference is _UNSET:
        reference = resolve_reference(
            raw, center_mode=center_mode, corner_fraction=corner_fraction,
            center_xy=center_xy, vacuum_shifts=vacuum_shifts,
            sig_shape=_sig_shape(signal))
    centered = apply_reference(raw, reference)

    nav_scale = _nav_scale(signal)
    estimate = None
    if auto_rotation or rotation is None:
        estimate = estimate_rotation(centered, mode=mode, nav_scale=nav_scale)
        if rotation is None:
            rotation, flip = estimate.angle, estimate.flip
    oriented = rotate_shifts(centered, float(rotation), flip=flip,
                             reverse=reverse)

    units, calibrated = "px", False
    field = oriented
    scale = mrad_per_px if mrad_per_px is not None else mrad_per_pixel(signal)
    if mode == "electric":
        energy = (beam_energy_kev if beam_energy_kev is not None
                  else beam_energy_kv(signal))
        if scale and thickness_nm and energy:
            field = to_electric_field(oriented, mrad_per_px=scale,
                                      thickness_nm=thickness_nm,
                                      beam_energy_kev=energy, like=signal)
            units, calibrated = "MV/cm", True
    elif scale:
        field, units, calibrated = oriented * float(scale), "mrad", True

    # One display rotation for the map AND its legend — see DISPLAY_ROTATION.
    return DpcResult(
        field=field, raw_shifts=raw, reference=reference, units=units,
        mode=mode, rotation=float(rotation), flip=bool(flip),
        reverse=bool(reverse),
        rgb=magnitude_phase_rgb(field, rotation=DISPLAY_ROTATION,
                                autolim_sigma=autolim_sigma),
        wheel=color_wheel_rgba(rotation=DISPLAY_ROTATION),
        centering=report, estimate=estimate,
        params={"method": method, "half_square_width": int(half_square_width),
                "center_mode": center_mode, "corner_fraction": corner_fraction,
                "thickness_nm": thickness_nm, "beam_energy_kev": beam_energy_kev,
                "mrad_per_px": scale, "calibrated": calibrated,
                # Recorded because it sets the RGB's display ceiling, which is
                # what the colour wheel's rim stands for. Without it the result
                # cannot say what its own picture is scaled to.
                "autolim_sigma": float(autolim_sigma),
                "beam_region": (region.as_dict() if region is not None
                                else BeamRegion().as_dict())},
    )


def _nav_scale(signal) -> tuple[float, float]:
    """``(dy, dx)`` navigation step, defaulting to 1 where uncalibrated."""
    try:
        nav = signal.axes_manager.navigation_axes
        dx = float(nav[0].scale) if len(nav) > 0 else 1.0
        dy = float(nav[1].scale) if len(nav) > 1 else 1.0
        return (dy or 1.0, dx or 1.0)
    except Exception:                                        # pragma: no cover
        return (1.0, 1.0)
